### ISSUE TITLE
ESPtime

### ISSUE THREAD

**Issue by bluechris** [lukasz-tuz/esphome-gui#2]
I get this error when i use your library 

`In file included from src/esphome/components/display/display_buffer.cpp:1:
src/esphome/components/display/display_buffer.h:276:99: error: 'esphome::time::ESPTime' has not been declared`

No matter what i do to get the time, your library wants the ESPtime so its not working.

I suppose this huppens because a fundamentally change huppent to ESPhome as matter the time

https://esphome.io/changelog/2023.6.0.html
`Move ESPTime into core esphome namespace [esphome#4926](https://github.com/esphome/esphome/pull/4926) by [@jesserockz](https://github.com/jesserockz) (breaking-change)`

**Comment by nielsnl68** [comment]
esphome-gui is based on the old display_buffer classes we are working on updating the code in a short while.

**Comment by bluechris** [comment]
Thank you for your work.

I am not in a rush, i just bought a Lilygo s3-Display Amoled that i tried with your library.
